MyImdb/Entities/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MyImdb.Entities
{
    public class Movie
    {
        public Guid Id { get; set; }

        public int Rank { get; set; }

        [MaxLength(100)]
        [Required]
        public string Title { get; set; }
        
        public int Year { get; set; }
        
        [MaxLength(200)]
        public string Storyline { get; set; }

        public DateTime CreationDateUtc { get; set; }

        [NotMapped]
        public DateTimeOffset CreationDate
        {
            get
            {
                return new DateTimeOffset(CreationDateUtc, TimeSpan.Zero);
            }
            set
            {
                CreationDateUtc = value.UtcDateTime;
            }
        }

		public Guid GenreId { get; set; }
		public Genre Genre { get; set; }

		public List<MovieActor> MovieActors { get; set; }
		#region
		public static List<Movie> SelectAll()
        {
            var movies = new List<Movie>()
            {
/*
                new Movie {Id=new Guid(1), Rank=9,Title="The Shawshank Redemption", Year=1994, Storyline="Two imprisoned men bond over a number of years"},
                new Movie {Id=2, Rank=9, Title="The Godfather", Year=1972, Storyline="The aging patriarch of an organized crime dynasty..." },
                new Movie {Id=3, Rank=9, Title="The Godfather - Part II", Year=1974, Storyline="The early life and career of Vito Corleone in 1920s..."},
                new Movie {Id=4, Rank=9, Title="The Dark Knight", Year=2008,Storyline="When the menace known as the Joker wreaks havoc..."}
            */
            };

            return movies;
        }

        public static List<Movie> SelectTopMovies()
        {
            var movies = new List<Movie>()
            {

                /*new Movie {Id=1, Rank=9,Title="The Shawshank Redemption", Year=1994, Storyline="Two imprisoned men bond over a number of years"},
                new Movie {Id=2, Rank=9, Title="The Godfather", Year=1972, Storyline="The aging patriarch of an organized crime dynasty..." },
                new Movie {Id=3, Rank=9, Title="The Godfather - Part II", Year=1974, Storyline="The early life and career of Vito Corleone in 1920s..."},
            */
            };
            return movies;
        }
        #endregion
    }
}

MyImdb/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyImdb.Models;
using MyImdb.ViewModels;
using MyImdb.Business.Services;
using MyImdb.Business.Repositories;
using MyImdb.Services;
using Api.Movies;
using MyImdb.Entities;

namespace MyImdb.Controllers
{
	[Route("api/movies")]
	[ApiController]
	public class MovieController : Controller
    {
		private readonly MovieService movieService;
		private readonly MovieRepository movieRepository;
		private readonly ModelConverter mc;
		public MovieController(MovieService movieService, MovieRepository movieRepository, ModelConverter mc) {
			this.movieService = movieService;
			this.movieRepository = movieRepository;
			this.mc = mc;
		}

		[HttpGet]
		public async Task<List<MovieModel>> List(int n = 20) {
			var movies = await movieRepository.SelectTopNAsync(n);

			return movies.ConvertAll(m => mc.ToModel(m));
		}

		[HttpGet("{id}")]
		public async Task<MovieModel> Get(Guid id) {
			var movie = await movieRepository.SelectByIdAsync(id);

			return mc.ToModel(movie);
		}


		[HttpPost]
		public async Task<MovieModel> Create(MovieData request) {
			var movie = await movieService.CreateAsync(request.Rank, request.Title, request.Year, request.Storyline, request.GenreId);

			return mc.ToModel(movie);
		}

		[HttpPut("{id}")]
		public async Task<MovieModel> Update(Guid id, MovieData request) {
			var movie = await movieRepository.SelectByIdAsync(id);

			await movieService.UpdateAsync(movie, request.Title, request.Rank, request.Storyline, request.Year, request.GenreId);

			return mc.ToModel(movie);
		}

		[HttpDelete("{id}")]
		public async Task Delete(Guid id) {
			var movie = await movieRepository.SelectByIdAsync(id);
			await movieService.DeleteAsync(movie);
		}

	}
}

MyImdb/Views/Movie/Create.cshtml
@model MyImdb.ViewModels.MovieCreateViewModel

@{
    Layout = "_Layout";
    ViewData["Title"] = "Create";
}


<h2>Add movie</h2>
<hr />
<h5>Please fill the movie data to add a new movie:</h5>

<form asp-controller="Movie" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group row">
        <label asp-for="Title" class="col-sm-2 col-form-label font-weight-bold"></label>
        <div class="col-sm-6">
            <input asp-for="Title" class="form-control" />
        </div>
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <label asp-for="Rank" class="col-sm-2 col-form-label font-weight-bold"></label>
        <div class="col-sm-3">
            <input asp-for="Rank" class="form-control" />
        </div>
        <span asp-validation-for="Rank" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <label asp-for="Year" class="col-sm-2 col-form-label font-weight-bold"></label>
        <div class="col-sm-3">
            <input asp-for="Year" class="form-control" />
        </div>
        <span asp-validation-for="Year" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <label asp-for="Storyline" class="col-sm-2 col-form-label font-weight-bold"></label>
        <div class="col-sm-6">
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" asp-for="Storyline"></textarea>
        </div>
        <span asp-validation-for="Storyline" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label font-weight-bold"> </label>
        <div class="col-sm-2">
            <button type="submit" value="Save" class="btn btn-warning text-white font-weight-bold">
                <i class="fa fa-check" aria-hidden="true"></i> &nbsp; Save
            </button>
        </div>
    </div>
</form>

<div>
    <a asp-controller="Movie" asp-action="Index"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back to Movies</a>
</div>

MyImdb/Views/Movie/Index.cshtml
@using MyImdb.ViewModels;
@model List<MovieListViewModel>
@{
    ViewData["Title"] = "Movies";
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    @if (ViewData.ContainsKey("msg"))
    {
        <div class="alert alert-info">
            <p>@ViewData["msg"]</p>
        </div>
    }
    <div class="h3">Movies</div>
    <br />
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Rank</th>
                <th scope="col">Year</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var movie in Model)
            {
                <tr>
                    <td>@movie.Title</td>
                    <td>@movie.Rank</td>
                    <td>@movie.Year</td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-area="" asp-controller="Movie" asp-action="Create" class="btn btn-light btn-md border-1 border-secondary">
        <i class="fa fa-plus" aria-hidden="true"></i>
        Add movie
    </a>
    <p class="mt-3">
        Click <a asp-area="" asp-controller="Movie" asp-action="MovieOfTheMonth">here</a> to check out the movie of the month.
    </p>

</body>
</html>

MyImdb/Views/Movie/MovieOfTheMonth.cshtml
@{
    ViewData["Title"] = "MovieOfTheMonth";
    Layout = "_Layout";
    var movieOfTheMonth = new {
        Rank = 1,
        Title = "The Shawshank Redemption",
        Year = 1994,
        StoryLine = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency"
    };
}

<h2>Movie of the Month</h2>

<div class="container ml-0 mb-3">
    <div class="row w-75 p-2 bg-light d-flex justify-content-start">
        <div class="col-sm-4 pr-0 d-flex justify-content-sm-center align-items-center" style="background-color: gray;">
            <i class="fa fa-video-camera fa-5x"></i>
        </div>
        <div class="col-sm-8">
            <div class="d-flex flex-column justify-content-start align-items-start">
                <p class="h4">@movieOfTheMonth.Title</p>
                <div class="d-flex flex-row">
                    <p class="font-weight-bold">Rank:&nbsp;</p>
                    <p>@movieOfTheMonth.Rank</p>
                </div>
                <div class="d-flex flex-row">
                    <p class="font-weight-bold">Director:&nbsp;</p>
                    <p>John Doe</p>
                </div>
                <p class="text-justify">@movieOfTheMonth.StoryLine</p>
                <div class="d-flex flex-row justify-content-between">
                    <button class="btn btn-sm bg-white border-1 rounded-sm border-dark mr-1">Watch Trailer</button>
                    <button class="btn btn-sm bg-white border-1 rounded-sm border-dark">Add to Watchlist</button>
                </div>
            </div>
        </div>
    </div>
</div>
<a asp-area="" asp-controller="Movie" asp-action="Index" class="mt-xl-5 p-1 text-info font-weight-bold"><i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;Back to Movies</a>